# GPUS: (0,1,2,3)
# WORKERS: 4
# PRINT_FREQ: 1

DDP_TRAIN: FALSE

DATASET:
  # DATASET_NAME: CIFAR10
  # ROOT: "../datasets"
  # ROOT_FOLDER: "./datasets/Cifar10"
  TRAIN_FOLDER: "/content/dataset/train"
  TRAIN_SAMPLE: 7000
  TEST_FOLDER: "/content/dataset/test"
  TEST_SAMPLE: 3000
  ZIP_FOLDER: "./datasets/Cifar10.zip"
  SELECTION_RATIO: 1
  SPLIT_RATIO: 0.7

DATASET_EXTRACT:
  DATASET_INFO: "../Info.csv"
  ZIP_FILE_PATH: "../Dataset/áº¢nh"
  EXTRACT_PATH: "../DTLHerb"
  MIN_IMG: 100
  MAX_IMG: 9999

TRAIN:
  DATA:
    IMAGE_SIZE: [256, 256]
    BATCH_SIZE: 64
    SHUFFLE: True
    MEAN:  [0.66645192, 0.66645192, 0.66645192]
    STD: [0.32449971, 0.32449971, 0.32449971]
  TRAIN_PARA:
    MODEL_TYPE: 1 #{1: Resnet50, 2: DenseNet201, 3: VGG19, 4: ConvNeXt_Large, 5: MobileNet}
    EMBEDDING_DIM: 512
    BEGIN_EPOCH: 0
    END_EPOCH: 100
    LAST_EPOCH: 0
    OPTIMIZER: "AdamW"
    RESUME: False
    EARLY_STOPPING: TRUE
    PATIENCE: 10
  OPTIONAL:
    SAVE_CHECKPOINT: TRUE
    CHECKPOINT_PATH: "./resume_model/checkpoint.pth"
    SAVE_BEST: TRUE
    BEST_PATH: "./best_model/best_checkpoint.pth"
    SAVE_METRICS: TRUE
    METRICS_PATH: "./metrics/metrics.csv"
  TRANSFORM: TRUE
  LEARNING_RATE:
    PieceWise:
      START_LR: 0.0001
      MAX_LR: 0.0005
      MIN_LR: 0.0001
      RAMPUP_EPOCHS: 10
      SUSTAIN_EPOCHS: 5
      EXP_DECAY: 0.8
    WarmupCosine: 
      START_LR: 0.00001
      MAX_LR: 0.00005
      MIN_LR: 0.00003
      RAMPUP_EPOCHS: 5
      SUSTAIN_EPOCHS: 30
      COS_DECAY: 15
TEST:
  BATCH_SIZE: 32

